name: Java Web Application CI-CD

on:
  push:
    branches:
      - main

jobs:

# ==================================================
# CI - BUILD + SONAR SCAN
# ==================================================

  build:
  
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
        cache: maven

    - name: Build WAR File
      run: |
        mvn clean package

    - name: SonarCloud Scan

      run: |
    
        mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
        -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.token=${{ secrets.SONAR_TOKEN }}

    - name: Upload WAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-war
        path: target/*.war


# ==================================================
# CD - AWS DEPLOYMENT
# ==================================================

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Download WAR
      uses: actions/download-artifact@v4
      with:
        name: application-war


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-2


# --------------------------------------------------
# Check Existing EC2
# --------------------------------------------------


    - name: Check EC2 Instance

      run: |

        INSTANCE_ID=$(aws ec2 describe-instances \

        --filters "Name=tag:Name,Values=Tomcat-server1" \
        "Name=instance-state-name,Values=running" \
        --query "Reservations[*].Instances[*].InstanceId" \
        --output text)

        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

        echo "Existing Instance: $INSTANCE_ID"


# --------------------------------------------------
# Create EC2 if not available
# --------------------------------------------------

    - name: Create RedHat EC2
      if: env.INSTANCE_ID == ''
      run: |

        INSTANCE_ID=$(aws ec2 run-instances \
        --image-id ami-02e3c96eaee2fe306 \
        --instance-type t3.micro \
        --key-name key-1 \
        --security-group-ids sg-05232a653e5e623fa \
        --tag-specifications \
        'ResourceType=instance,Tags=[{Key=Name,Value=Tomcat-server1}]' \
        --user-data file://install-tomcat.sh \
        --query 'Instances[0].InstanceId' \
        --output text)

        echo "Created EC2: $INSTANCE_ID"

        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
        
        
# --------------------------------------------------
# Wait for EC2
# --------------------------------------------------

    - name: Wait for EC2
      run: |
          sleep 120
# --------------------------------------------------
# Get EC2 Public IP
# --------------------------------------------------

    - name: Get EC2 Public IP
      run: |

        PUBLIC_IP=$(aws ec2 describe-instances \
        --filters "Name=tag:Name,Values=Tomcat-server1" \
        "Name=instance-state-name,Values=running" \
        --query "Reservations[*].Instances[*].PublicIpAddress" \
        --output text)

        echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

        echo "Server IP: $PUBLIC_IP"
        
    - name: Configure SSH Key
      run: |
      
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2-key.pem
        chmod 600 ec2-key.pem


# --------------------------------------------------
# Deploy WAR to Tomcat
# --------------------------------------------------

    - name: Deploy WAR File
      run: |

        scp -i ec2-key.pem -o StrictHostKeyChecking=no \
        target/*.war \
        ec2-user@${{ env.PUBLIC_IP }}:/opt/tomcat/webapps/


    - name: Restart Tomcat
      run: |

        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@${{ env.PUBLIC_IP }} << EOF
        /opt/tomcat/bin/shutdown.sh
        sleep 10
        /opt/tomcat/bin/startup.sh
        EOF

# --------------------------------------------------
# Display Application URL
# --------------------------------------------------

    - name: Display Application URL
      run: |

        echo "Application is deployed successfully"
        echo "Application URL: http://${{ env.PUBLIC_IP }}:8080/assignment1-harshitha"


